### ISSUE TITLE
how to make statuscolumn work?

### ISSUE THREAD

**Issue by daUnknownCoder** [OXY2DEV/nvim#1]
i came from this [reddit convo](https://www.reddit.com/r/neovim/comments/1djjc6q/comment/l9fk83u/?utm_source=share&utm_medium=web2x&context=3)

so how to make it work? do i have to download the `custom_plugin` folder into my config and disable `statusline`, `tabline` and then require `bars.lua` in my `init.lua`?

**Comment by OXY2DEV** [comment]
You can't currently only get the `statuscolumn` as it was meant for **personal use**. If you try calling `require("bars").setup()` it will also replace your `tabline` & `statusline`.

It is not recommended to use anything inside the `custom_plugins/` folder as they have 0 documentation & are **not** tested on other machines.

>[!NOTE]
>If you still wish to use **only the statuscolumn** then comment out line ~~208~~ **268** & ~~209~~ **269** in the `custom_plugins/bars-N-lines.nvim/lua/bars.lua` file.

**Comment by daUnknownCoder** [comment]
> [!NOTE]
> If you still wish to use only the statuscolumn then comment out line *208* & *209* in the `custom_plugins/bars-N-lines.nvim/lua/bars.lua` file.

![image](https://github.com/OXY2DEV/nvim/assets/84800625/18c10ceb-e777-4f59-a80e-645977fdb09a)

i think you r telling me the wrong line

**Comment by daUnknownCoder** [comment]
btw are u talking about `falsing` things on *124* and *134*

**Comment by OXY2DEV** [comment]
My bad. I forgot that I didn't push changes yet.

I meant [this line](https://github.com/OXY2DEV/nvim/blob/8fb09c17adc201e1ef39b32be2d8cfaec6e5b0df/lua/custom_plugins/bars-N-lines.nvim/lua/bars.lua#L268) and the one after it.

**Comment by daUnknownCoder** [comment]
> My bad. I forgot that I didn't push changes yet.
> 
> I meant [this line](https://github.com/OXY2DEV/nvim/blob/8fb09c17adc201e1ef39b32be2d8cfaec6e5b0df/lua/custom_plugins/bars-N-lines.nvim/lua/bars.lua#L268) and the one after it.

ok and do i have any options if i only wanna copypasta statuscolumn.lua? coz i have to add other stuff in there as lsp and gitsigns thats why i was trying to get the statuscolumn.lua to work which only gets me 4 blank lines

**Comment by OXY2DEV** [comment]
Unfortunately, no.

The whole thing isn't meant to be compatible with other plugins. Plus, it runs on `per window` so just calling the `init` function isn't going to be enough.

**Comment by daUnknownCoder** [comment]
funny enough i was trying to get that work with: https://github.com/luukvbaal/statuscol.nvim

but ill be closing this for now
