### ISSUE TITLE
how do we install bars-N-lines.nvim?

### ISSUE THREAD

**Issue by daUnknownCoder** [OXY2DEV/nvim#2]
tried this:
```lua
  "https://github.com/OXY2DEV/nvim/blob/main/lua/custom_plugins/bars-N-lines.nvim", -- also tried: "OXY2DEV/bars-N-lines.nvim",
  name = "bars",
  event = "LazyFile",
  lazy = true,
  config = function()
    require("bars").setup({
      default = {
        statuscolumn = {
          enable = true,
          options = {},
        },
        statusline = {
          enable = false,
          options = {},
        },

        tabline = {
          enable = false,
          options = {},
        },
      },
    })
  end,
```

but this doesnt work

**Comment by OXY2DEV** [comment]
You can't(**at the moment**) install it without cloning the folder locally and using `dir` in `lazy.nvim`.

The plugin still has a few minor bugs and it might not integrate with other plugins(such as `gitsigns.nvim`).

I suggest you wait for me to finish developing(and writing docs for it) it.

I will publish it in a separate repo to make it installable.
