### ISSUE TITLE
colors.nvim, foldtex.nvim and helpview.nvim are missing

### ISSUE THREAD

**Issue by manumoreno** [OXY2DEV/nvim#4]
Hi there, I just cloned your repo. I really like the customization you're doing. However, it appears that 3 plugins are missing from `custom_plugins`.

```
colors.nvim
foldtext.nvim
helpview.nvim
```

Do you have a copy of them in your repo by any chance?

**Comment by OXY2DEV** [comment]
That's just how `git` works. All 3 of those plugins have their own repo so are not included when commiting changes.

Since I work on them locally it doesn't make sense to install them via git. So, they won't be installed(unless you changed the respective config file under `lua/plugins/`).

**Comment by manumoreno** [comment]
Nevermind. Found them! Thanks
